create_from_crs_strings – fproj
create_from_crs_strings Subroutine
9 statements
Source File
public subroutine create_from_crs_strings(my_transformer, string_from, string_to)
Type Bound
transformer
Arguments
Type Intent Optional Attributes Name
class(transformer) :: my_transformer
character(len=*) :: string_from
character(len=*) :: string_to
Calls
Source Code
    subroutine create_from_crs_strings(my_transformer,string_from,string_to)
!========================================================================================
        class(transformer) :: my_transformer
        character(len=*) :: string_from,string_to
!
        if(starts_with(string_from,"EPSG:") .and. starts_with(string_to,"EPSG:")) then
            my_transformer%pj_obj = proj_create_crs_to_crs(&
                pj_context_default, &
                trim(string_from)//c_null_char, &
                trim(string_to)//c_null_char,&
                my_transformer%area);
        else
            call error_stop(msg="The EPSG codes do not start with EPSG:");
        endif
    end subroutine create_from_crs_strings
Call graph
create_from_crs_strings calls error_stop, proj_create_crs_to_crs, starts_with