destroy_transformer –
destroy_transformer Subroutine
12 statements
Source File
public subroutine destroy_transformer(my_transformer)
Type Bound
transformer
Arguments
Type Intent Optional Attributes Name
class(transformer) :: my_transformer
Calls
Source Code
    subroutine destroy_transformer(my_transformer)
!========================================================================================
        class(transformer) :: my_transformer
!
        if(allocated(my_transformer%coord_values)) then
            deallocate(my_transformer%coord_values);
        endif
!
        if(allocated(my_transformer%original_values)) then
            deallocate(my_transformer%original_values);
        endif
!
        call my_transformer%from%destroy();
        call my_transformer%to%destroy();
!
        my_transformer%pj_obj=proj_destroy(my_transformer%pj_obj);
!
    end subroutine destroy_transformer
Call graph
destroy_transformer calls destroy_crs, proj_destroy
destroy_crs calls proj_destroy